In [3]:
import numpy as np

a = np.array([1.7, 4.0, 3.1])

exp_a = np.exp(a)    #지수 함수 (분모)
print(exp_a)

sum_exp_a = np.sum(exp_a)  #지수 합수의 합 (분자)
print(sum_exp_a)

y = exp_a / sum_exp_a    #소프트맥스 함수 식
print(y)

[ 5.47394739 54.59815003 22.19795128]
82.27004870631308
[0.06653633 0.66364553 0.26981814]


In [4]:
def softmax(x):
    exp_x = np.exp(x)
    sum_exp_x = np.sum(exp_x)
    y = exp_x / sum_exp_x
    
    return y

In [7]:
a = np.array([1010, 1000, 990])
np.exp(a) / np.sum(np.exp(a))  #소프트맥스 함수 계산

<ipython-input-7-3094c65d7e4b>:2: RuntimeWarning: overflow encountered in exp
  np.exp(a) / np.sum(np.exp(a))  #소프트맥스 함수 계산
<ipython-input-7-3094c65d7e4b>:2: RuntimeWarning: invalid value encountered in true_divide
  np.exp(a) / np.sum(np.exp(a))  #소프트맥스 함수 계산


array([nan, nan, nan])

In [8]:
c = np.max(a)         # c = 1010 최댓값
a - c

array([  0, -10, -20])

In [9]:
np.exp(a-c) / np.sum(np.exp(a-c))

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

In [ ]:
def softmax(a):
    c = mp.max(a)
    exp_a = np.exp(a -c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

In [11]:
a = np.array([1.1, 2.4, 4.8])
y = softmax(a)
print(y)
np.sum(y)

[0.02216479 0.08132919 0.89650602]


1.0